<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Wie-kann-man-aus-einer-Liste-alle-Einträge-x-löschen?" data-toc-modified-id="Wie-kann-man-aus-einer-Liste-alle-Einträge-x-löschen?-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Wie kann man aus einer Liste alle Einträge x löschen?</a></span></li><li><span><a href="#Parameter-im-JSON-Format-speichern-und-wieder-einlesen" data-toc-modified-id="Parameter-im-JSON-Format-speichern-und-wieder-einlesen-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Parameter im JSON Format speichern und wieder einlesen</a></span><ul class="toc-item"><li><span><a href="#Parameter-im-JSON-Format-speichern" data-toc-modified-id="Parameter-im-JSON-Format-speichern-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Parameter im JSON-Format speichern</a></span></li><li><span><a href="#Parameter-aus-JSON-Datei-einlesen" data-toc-modified-id="Parameter-aus-JSON-Datei-einlesen-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Parameter aus JSON-Datei einlesen</a></span></li></ul></li><li><span><a href="#Bündige-Ausgaben-mit-Format" data-toc-modified-id="Bündige-Ausgaben-mit-Format-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Bündige Ausgaben mit Format</a></span></li><li><span><a href="#Wozu-der-@staticmethod-Function-Decorator?" data-toc-modified-id="Wozu-der-@staticmethod-Function-Decorator?-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Wozu der <code>@staticmethod</code> Function Decorator?</a></span></li><li><span><a href="#hdf5-Format" data-toc-modified-id="hdf5-Format-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>hdf5 Format</a></span><ul class="toc-item"><li><span><a href="#Mal-Daten-im-hdf5-Format-wegschreiben" data-toc-modified-id="Mal-Daten-im-hdf5-Format-wegschreiben-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Mal Daten im hdf5 Format wegschreiben</a></span></li><li><span><a href="#Daten-wieder-einlesen" data-toc-modified-id="Daten-wieder-einlesen-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Daten wieder einlesen</a></span></li><li><span><a href="#Keys-einer-hdf5-Datei-ausgeben" data-toc-modified-id="Keys-einer-hdf5-Datei-ausgeben-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Keys einer hdf5 Datei ausgeben</a></span></li><li><span><a href="#Datasets-sind-nur-Referenzen-auf-die-Daten,-nicht-die-Daten-selber!" data-toc-modified-id="Datasets-sind-nur-Referenzen-auf-die-Daten,-nicht-die-Daten-selber!-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>Datasets sind nur Referenzen auf die Daten, nicht die Daten selber!</a></span></li><li><span><a href="#Daten-auch-nach-Schließen-noch-verfügbar-machen" data-toc-modified-id="Daten-auch-nach-Schließen-noch-verfügbar-machen-5.5"><span class="toc-item-num">5.5&nbsp;&nbsp;</span>Daten auch nach Schließen noch verfügbar machen</a></span></li><li><span><a href="#Daten-ändern" data-toc-modified-id="Daten-ändern-5.6"><span class="toc-item-num">5.6&nbsp;&nbsp;</span>Daten ändern</a></span></li><li><span><a href="#Datentyp-für-Datensatz-festlegen" data-toc-modified-id="Datentyp-für-Datensatz-festlegen-5.7"><span class="toc-item-num">5.7&nbsp;&nbsp;</span>Datentyp für Datensatz festlegen</a></span></li><li><span><a href="#Kompression" data-toc-modified-id="Kompression-5.8"><span class="toc-item-num">5.8&nbsp;&nbsp;</span>Kompression</a></span></li><li><span><a href="#Gruppen-Organisationsprinzip" data-toc-modified-id="Gruppen-Organisationsprinzip-5.9"><span class="toc-item-num">5.9&nbsp;&nbsp;</span>Gruppen-Organisationsprinzip</a></span></li><li><span><a href="#Gruppen-ausgeben" data-toc-modified-id="Gruppen-ausgeben-5.10"><span class="toc-item-num">5.10&nbsp;&nbsp;</span>Gruppen ausgeben</a></span></li><li><span><a href="#Metadaten-speichern" data-toc-modified-id="Metadaten-speichern-5.11"><span class="toc-item-num">5.11&nbsp;&nbsp;</span>Metadaten speichern</a></span></li><li><span><a href="#Metadaten-wieder-ausgeben" data-toc-modified-id="Metadaten-wieder-ausgeben-5.12"><span class="toc-item-num">5.12&nbsp;&nbsp;</span>Metadaten wieder ausgeben</a></span></li></ul></li></ul></div>

# Wie kann man aus einer Liste alle Einträge x löschen?

In [2]:
L = [2,4,6,8,10,8,12,8,8]

In [3]:
L.remove(8)

In [4]:
L

[2, 4, 6, 10, 8, 12, 8, 8]

Lösung mittels List-Comprehension:

In [8]:
[i for i in L if i != 8]

[2, 4, 6, 10, 12]

Lösung mittels while-Schleife und in-Operator:

In [9]:
L = [2,4,6,8,10,8,12,8,8]

In [10]:
8 in L

True

In [11]:
while 8 in L:
    L.remove(8)

In [12]:
L

[2, 4, 6, 10, 12]

Achtung! Die zweite Lösung ist ineffizient. Weil wir `remove()` immer wieder neu aufrufen, muss immer wieder neu durch die Liste L gegangen werden!

# Parameter im JSON Format speichern und wieder einlesen

## Parameter im JSON-Format speichern

In [52]:
params = { "sensor": "druck", "abtastrate": 0.123, "alpha": 25, \
           "weiteres" : [1,2,3,4,5,6] }

In [53]:
import json

In [54]:
fobj = open("meine_json_datei.json", "w")

In [55]:
json.dump(params, fobj, indent=4, sort_keys=True)

In [56]:
fobj.close()

## Parameter aus JSON-Datei einlesen

In [57]:
import json

In [58]:
fobj2 = open("meine_json_datei.json", "r")

In [59]:
data = json.load(fobj2)

In [60]:
data

{'abtastrate': 0.123,
 'alpha': 25,
 'sensor': 'druck',
 'weiteres': [1, 2, 3, 4, 5, 6]}

In [61]:
type(data)

dict

In [62]:
data["abtastrate"]

0.123

# Bündige Ausgaben mit Format

In [1]:
zk1 = "Dies ist ein sehr sehr langer Text"
zk2 = "Kurzer Text"
z1 = 123
z2 = 4.56789

Textfeld mit 60 Zeichen. Rechtsbünding ausgeben.

In [5]:
print("{0:>60}".format(zk1))

                          Dies ist ein sehr sehr langer Text


Textfeld mit 60 Zeichen. Linksbündig ausgeben.

In [6]:
print("{0:<60}".format(zk1))

Dies ist ein sehr sehr langer Text                          


Textfeld mit 60 Zeichen. Zentriert ausgeben.

In [7]:
print("{0:^60}".format(zk1))

             Dies ist ein sehr sehr langer Text             


Textfeld mit 60 Zeichen. Dann Leerzeichen, dann nächster Parameter.

In [18]:
print("{0:40}: {1}".format(zk1,z1))

Dies ist ein sehr sehr langer Text      :123


In [19]:
print("{0:40}: {1}".format(zk1,z1))
print("{0:40}: {1}".format(zk2,z2))

Dies ist ein sehr sehr langer Text      : 123
Kurzer Text                             : 4.56789


Beide Zahlen rechtsbündig ausgeben:

In [20]:
print("{0:40}: {1:>10}".format(zk1,z1))
print("{0:40}: {1:>10}".format(zk2,z2))

Dies ist ein sehr sehr langer Text      :        123
Kurzer Text                             :    4.56789


Füllzeichen für Textfeld = .

Füllzeichen für Zahlenfeld = _

In [29]:
print("{0:.<40}: {1:_>10}".format(zk1,z1))
print("{0:.<40}: {1:_>10}".format(zk2,z2))

Dies ist ein sehr sehr langer Text......: _______123
Kurzer Text.............................: ___4.56789


Führende Nullen bei Zahl:

In [54]:
print("{0:.<40}: {1:0>10}".format(zk1,z1))
print("{0:.<40}: {1:0>10}".format(zk2,z2))

Dies ist ein sehr sehr langer Text......: 0000000123
Kurzer Text.............................: 0004.56789


Zwei Nachkommastellen Genauigkeit bei gebrochener Zahl:

In [55]:
print("{0:.<40}: {1:0>10}".format(zk1,z1))
print("{0:.<40}: {1:0>10.2f}".format(zk2,z2))

Dies ist ein sehr sehr langer Text......: 0000000123
Kurzer Text.............................: 0000004.57


# Wozu der `@staticmethod` Function Decorator?

Das fragen sich auch andere:

https://stackoverflow.com/questions/43587044/do-we-really-need-staticmethod-decorator-in-python-to-declare-static-method

In [56]:
class A:
    def foo():
        print("Hallo!")

In [58]:
A.foo()

Hallo!


In [59]:
a1 = A()

Folgender Aufruf geht nicht:

In [60]:
a1.foo()

TypeError: foo() takes 0 positional arguments but 1 was given

Mit dem Dekorator `@staticmethod` geht der Aufruf dann aber doch, d.h. dass wir dann auch die Methode von einer Instanzvariablen (einem Objekt) der Klasse A aufrufen können:

In [62]:
class A:
    
    @staticmethod
    def foo():
        print("Hallo!")

In [63]:
a1 = A()

In [64]:
A.foo()

Hallo!


In [65]:
a1.foo()

Hallo!


# hdf5 Format

## Mal Daten im hdf5 Format wegschreiben

In [11]:
import h5py
import numpy as np

arr1 = np.random.randn(1000)
arr2 = np.random.randn(1000)

print(min(arr1))
print(max(arr1))
print(arr1[:5])

print(min(arr2))
print(max(arr2))
print(arr2[:5])

f = h5py.File('random.hdf5', 'w')
dset = f.create_dataset("arr1", data=arr1)
dset = f.create_dataset("arr2", data=arr2)
f.close()

-2.70550911672
3.11822477431
[ 0.86285881  0.23717803 -1.4260296   0.19701277  0.2333283 ]
-3.50676618597
3.64805502772
[ 0.86353139 -1.29826831 -0.51647234  1.42388143 -0.17552074]


## Daten wieder einlesen

In [17]:
f = h5py.File('random.hdf5', 'r')

arr1_dataset = f['arr1']
print(type(arr1_dataset))
print(min(arr1_dataset))
print(max(arr1_dataset))
print(arr1_dataset[:5])

arr2_dataset = f['arr2']
print(type(arr2_dataset))
print(min(arr2_dataset))
print(max(arr2_dataset))
print(arr2_dataset[:5])

f.close()

<class 'h5py._hl.dataset.Dataset'>
-2.70550911672
3.11822477431
[ 0.86285881  0.23717803 -1.4260296   0.19701277  0.2333283 ]
<class 'h5py._hl.dataset.Dataset'>
-3.50676618597
3.64805502772
[ 0.86353139 -1.29826831 -0.51647234  1.42388143 -0.17552074]


## Keys einer hdf5 Datei ausgeben

In [15]:
f = h5py.File('random.hdf5', 'r')
for key in f.keys():
    print(key)
f.close()

arr1
arr2


## Datasets sind nur Referenzen auf die Daten, nicht die Daten selber!

In [20]:
f = h5py.File('random.hdf5', 'r')

arr1_dataset = f['arr1']
print(type(arr1_dataset))
print(min(arr1_dataset))
print(max(arr1_dataset))
print(arr1_dataset[:5])
print("Eintrag mit Index 42 = ", arr1_dataset[42])

f.close()

# Das wird schief gehen, weil die Datei schon zu ist
# Damit funktioniert die Referenz auf die Daten nicht mehr
# Datasets sind nur Referenzen auf die Daten,
# nicht die Daten selber!
#print("Eintrag mit Index 42 = ", arr1_dataset[42])

<class 'h5py._hl.dataset.Dataset'>
-2.70550911672
3.11822477431
[ 0.86285881  0.23717803 -1.4260296   0.19701277  0.2333283 ]
Eintrag mit Index 42 =  0.499495351078


## Daten auch nach Schließen noch verfügbar machen

In [23]:
f = h5py.File('random.hdf5', 'r')

arr1_dataset = f['arr1']

print(min(arr1_dataset))
print(max(arr1_dataset))
print(arr1_dataset[:5])
print("Eintrag mit Index 42 = ", arr1_dataset[42])
print(type(arr1_dataset))

data = arr1_dataset[:43]

f.close()

# Das wird schief gehen, weil die Datei schon zu ist
# Damit funktioniert die Referenz auf die Daten nicht mehr
# Datasets sind nur Referenzen auf die Daten,
# nicht die Daten selber!
print("Eintrag mit Index 42 = ", data[42])
print(type(data))

-2.70550911672
3.11822477431
[ 0.86285881  0.23717803 -1.4260296   0.19701277  0.2333283 ]
Eintrag mit Index 42 =  0.499495351078
<class 'h5py._hl.dataset.Dataset'>
Eintrag mit Index 42 =  0.499495351078
<class 'numpy.ndarray'>


## Daten ändern

Daten schreiben:

In [17]:
import h5py
f = h5py.File('ein_paar_daten.hdf5', 'w')
dset = f.create_dataset("arr1", data=[1,2,3])
f.close()

Daten wieder einlesen:

In [18]:
f = h5py.File('ein_paar_daten.hdf5', 'r')
dset = f["arr1"]
print(dset[:])
f.close()

[1 2 3]


Daten mal abändern:

In [21]:
import h5py
f = h5py.File('ein_paar_daten.hdf5', 'r+') # Achtung! "r+" !
dset = f["arr1"]
print(dset[:])

# Daten ändern
dset[0] = dset[0]+1

f.close()

[3 2 3]


## Datentyp für Datensatz festlegen

In [31]:
import numpy as np
arr = np.random.randn(100000)

f = h5py.File('integer_1.hdf5', 'w')
d = f.create_dataset('dataset', (100000,), dtype='i1')
d[:] = arr
f.close()

f = h5py.File('integer_8.hdf5', 'w')
d = f.create_dataset('dataset', (100000,), dtype='i8')
d[:] = arr
f.close()

## Kompression

In [33]:
import h5py
import numpy as np

arr = np.random.randn(100000)

with h5py.File('integer_1_compr.hdf5', 'w') as f:
    d = f.create_dataset('dataset', (100000,), dtype='i1', compression="gzip", compression_opts=9)
    d[:] = arr

with h5py.File('integer_8_compr.hdf5', 'w') as f:
    d = f.create_dataset('dataset', (100000,), dtype='i8', compression="gzip", compression_opts=9)
    d[:] = arr

## Gruppen-Organisationsprinzip

In [34]:
import numpy as np
import h5py

arr = np.random.randn(1000)

with h5py.File('groups.hdf5', 'w') as f:
    g = f.create_group('Base_Group')
    gg = g.create_group('Sub_Group')

    d = g.create_dataset('default', data=arr)
    dd = gg.create_dataset('default', data=arr)

In [35]:
with h5py.File('groups.hdf5', 'r') as f:
    d = f['Base_Group/default']
    dd = f['Base_Group/Sub_Group/default']
    print(d[1])
    print(dd[1])

-2.8012220308
-2.8012220308


## Gruppen ausgeben

In [36]:
with h5py.File('groups.hdf5', 'r') as f:
    for k in f.keys():
        print(k)

Base_Group


Problem: wir müssen das rekursiv machen!

Deswegen gibt es eine `visit()` Methode:

In [39]:
def get_all(name):
   print(name)

with h5py.File('groups.hdf5', 'r') as f:
    print(type(f))
    f.visit(get_all)

<class 'h5py._hl.files.File'>
Base_Group <class 'str'>
Base_Group/Sub_Group <class 'str'>
Base_Group/Sub_Group/default <class 'str'>
Base_Group/default <class 'str'>


## Metadaten speichern

In [42]:
import numpy as np
import h5py

mu1 = 5
mu2 = -5
arr1 = np.random.normal(mu1,10,1000)
arr2 = np.random.normal(mu2,10,1000)

with h5py.File('groups.hdf5', 'w') as f:
    g = f.create_group('Base_Group')
    g.attrs["Infos"] = "Das ist die Basisgruppe"
    
    gg = g.create_group('Sub_Group')
    gg.attrs["Infos"] = "Das ist ne Untergruppe"

    d = g.create_dataset('default', data=arr1)
    d.attrs["Mean"] = mu1
    
    dd = gg.create_dataset('default', data=arr2)
    dd.attrs["Mean"] = mu2

In [43]:
def get_all(name):
   print(name)

with h5py.File('groups.hdf5', 'r') as f:
    print(type(f))
    f.visit(get_all)

<class 'h5py._hl.files.File'>
Base_Group
Base_Group/Sub_Group
Base_Group/Sub_Group/default
Base_Group/default


## Metadaten wieder ausgeben

In [46]:
with h5py.File('groups.hdf5', 'r') as f:
    d = f['Base_Group/default']
    dd = f['Base_Group/Sub_Group/default']
    print(d[1], d.attrs["Mean"])
    print(dd[1], dd.attrs["Mean"])

13.4153969435 5
-0.30300026668 -5
